name: Workflow
on:
  push:
    branches:
      - dev
      - master
      - vcho
  pull_request:
    branches:
      - '!master'
jobs:
  build:
    name: windows-2022
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name : Change Directory
        run: cd src
      - name: Run Nuke Build
        run: ./build.cmd --GitHubToken ${{ secrets.GITHUB_TOKEN }}